//All mp3 data storage

let data = [
    {name:'a-aahno-nooh', inList:true},
    {name:'aaah', inList:true},
    {name:'amaverjine', inList:true},
    {name:'beepsheep', inList:true},
    {name:'boswer', inList:true},
    {name:'boswerhaha', inList:true},
    {name:'braindamgae', inList:true},
    {name:'choke', inList:true},
    {name:'cvedir', inList:true},
    {name:'davidG', inList:true},
    {name:'diabeetus', inList:true},
    {name:'dkrap', inList:true},
    {name:'enui', inList:true},
    {name:'epe', inList:true},
    {name:'Fart Meme Sound', inList:true},
    {name:'Fart sound effect', inList:true},
    {name:'ga-non', inList:true},
    {name:'gamme', inList:true},
    {name:'grilled', inList:true},
    {name:'heput', inList:true},
    {name:'jépapété', inList:true},
    {name:'Le Monke\'s Fart Sound Effect', inList:true},
    {name:'lotadamej', inList:true},
    {name:'newdog', inList:true},
    {name:'nodontdoit', inList:true},
    {name:'nop', inList:true},
    {name:'Normal Fart Sound Effect.', inList:true},
    {name:'nuaj', inList:true},
    {name:'ogpt', inList:true},
    {name:'ogpt2', inList:true},
    {name:'ogpt3', inList:true},
    {name:'pet1', inList:true},
    {name:'pet2', inList:true},
    {name:'pet3', inList:true},
    {name:'pet4', inList:true},
    {name:'pet5', inList:true},
    {name:'pet6', inList:true},
    {name:'pet7', inList:true},
    {name:'pet8', inList:true},
    {name:'pet9', inList:true},
    {name:'pet10', inList:true},
    {name:'photo', inList:true},
    {name:'picnic', inList:true},
    {name:'Quick Reverb Fart - Sound Effect (HD)', inList:true},
    {name:'realman', inList:true},
    {name:'sanfe', inList:true},
    {name:'sike', inList:true},
    {name:'spaghet', inList:true},
    {name:'stegosaurus', inList:true},
    {name:'trompet', inList:true},
    {name:'yapadson', inList:true},
    {name:'yeet', inList:true},
    {name:'yrug', inList:true},
    {name:'yt1s.com - Loudest orgasm ever earrape edition WARNING EARRAPE', inList:true}
]