//All mp3 filenames

const audioNames = [
    "A society",
    "aaah",
    "Aah noo",
    "Ali-A",
    "Amaverjin",
    "AVC",
    "Ayeet",
    "Balls",
    "Bandicoot",
    "Baptiste",
    "Beep sheep",
    "Bing chilling",
    "boswer",
    "Braindamage",
    "Brefs délais",
    "Chicks",
    "choke",
    "Chomage",
    "Chug jug",
    "Cocaina",
    "Cyberchaj asmr",
    "Damage",
    "Despacito 2",
    "Despacito",
    "diabeetus",
    "Disappointment",
    "Disperse fart",
    "DK rap",
    "Don't do it",
    "Drip",
    "Emergency",
    "Ennui",
    "Epee",
    "Ey wha",
    "Fart sound effect",
    "Fortnite default",
    "Funeste Chorale",
    "ga-non",
    "Geinoz-Cide",
    "Grave fart",
    "Grill",
    "Gucci",
    "Hahuh",
    "hanji",
    "Heebitch",
    "Help",
    "Humid fart",
    "It's Mario",
    "Jeff",
    "Juice",
    "K compote",
    "K feu",
    "K gra",
    "K pafo",
    "K poulette",
    "K pute",
    "K scorpion",
    "K sporadick",
    "K stache",
    "K Wales",
    "Lazy town",
    "Long fart",
    "Long name",
    "Loon fart",
    "Loudest orgasm",
    "Luke",
    "Mario fall",
    "Mario jump",
    "Mickey fart",
    "Mission failed",
    "moan",
    "Moist",
    "Music",
    "Mwahaha",
    "Nani",
    "Negus",
    "New dog",
    "No sound",
    "Non",
    "Nuage",
    "Ogpt 2",
    "Ogpt 3",
    "ogpt",
    "pain",
    "picnic",
    "Poop fart",
    "projet",
    "Pufferfish",
    "Putin",
    "Question fart",
    "Quick fart",
    "Quick Reverb Fart",
    "Real man",
    "richelieu",
    "samsung",
    "Sans feu",
    "Shart",
    "Short fart",
    "Shut up when I'm talking",
    "sike",
    "Skrrra",
    "snore",
    "Spaghetti",
    "Speedrun",
    "stegosaurus",
    "Stink fart",
    "Suck somebody",
    "supercell",
    "Sus fart",
    "The f you say",
    "Toon 1",
    "Toon 2",
    "Toon 3",
    "Toon 4",
    "Toon 5",
    "Trebble fart",
    "Tyler1",
    "v_dorian",
    "v_Fromage",
    "We like Fortnite",
    "What it is",
    "What u on abt",
    "What",
    "windows",
    "xue",
    "Y u ge",
    "Y u run",
    "yamete",
    "Yayeet",
    "Yeet",
]