//All mp3 filenames

const audioNames = [
    "A society",
    "A",
    "aaah",
    "Aah noo",
    "Abominatogus",
    "Ali-A",
    "Amaverjin",
    "Amoamogus",
    "Amogus",
    "Asmolgus",
    "AVC",
    "Ayeet",
    "Balls",
    "Bandicoot",
    "Baptiste",
    "Beep sheep",
    "Bing chilling",
    "boswer",
    "Brain damage",
    "Brain fart",
    "Brefs délais",
    "Chalet familial",
    "Chicks",
    "choke",
    "Chomage",
    "Chug jug",
    "Cocaina",
    "Cyberchaj asmr",
    "Damage",
    "Damaged 2",
    "Damaged",
    "Despacito 2",
    "Despacito",
    "diabeetus",
    "Disappointment",
    "Disperse fart",
    "DK rap",
    "Don't do it",
    "Drip",
    "Dégueulasse",
    "Eau",
    "Emergency",
    "Ennui",
    "Epee",
    "Ey wha",
    "Fanta décide",
    "Fanta TG",
    "Fart sound effect",
    "Fortnite default",
    "Funeste Chorale",
    "ga-non",
    "Geinoz-Cide",
    "Giraffe",
    "Godwin",
    "Grave fart",
    "Grill",
    "Gros nounours",
    "Gucci",
    "Hahuh",
    "hanji",
    "Heebitch",
    "Help",
    "Humid fart",
    "It's Mario",
    "J dream",
    "J Hayato",
    "J lero",
    "J Mohamedo Avudolu",
    "J muda",
    "J no",
    "J oh no",
    "J omg",
    "J roadroller da",
    "J soab",
    "J yes",
    "J ZA WARUDO",
    "Janoskour",
    "Jeff",
    "Juice",
    "Juillet",
    "K compote",
    "K feu",
    "K gra",
    "K pafo",
    "K poulette",
    "K pute",
    "K scorpion",
    "K sporadick",
    "K stache",
    "K Wales",
    "Katy Perry",
    "Lafarge",
    "Lazy town",
    "Le Grand Monarque",
    "Long fart",
    "Long name",
    "Loon fart",
    "Loudest orgasm",
    "Luke",
    "Lynx",
    "Marine",
    "Mario fall",
    "Mario jump",
    "Mickey fart",
    "Mission failed",
    "moan",
    "Moist",
    "Mother Earth",
    "Motus",
    "Music",
    "Mwahaha",
    "Médaillon",
    "Nani",
    "Negus",
    "New dog",
    "Niaiseries",
    "Nils",
    "No sound",
    "Non",
    "Nuage",
    "Ogpt 2",
    "Ogpt 3",
    "ogpt",
    "On est quittes",
    "Orteils",
    "Où est-il",
    "pain",
    "Perlimpinpin",
    "picnic",
    "Poop fart",
    "Poète",
    "Poésie",
    "projet",
    "Pufferfish",
    "Putin",
    "Quenouilles",
    "Question fart",
    "Quick fart",
    "Rasengan",
    "Real man",
    "Reverb fart",
    "richelieu",
    "Rigodon",
    "Romantique",
    "Ronaldo",
    "Roucoule",
    "Salut",
    "samsung",
    "Sans feu",
    "Sardo",
    "Sarko",
    "Semaine",
    "Shart",
    "Short fart",
    "Shut up when I'm talking",
    "sike",
    "Skrrra",
    "snore",
    "Spaghet",
    "Spaghetti",
    "Speedrun",
    "Spiderman",
    "Squalala",
    "stegosaurus",
    "Stink fart",
    "Suck somebody",
    "Sugoma",
    "Sugus",
    "supercell",
    "Sus fart",
    "Terrorisme",
    "TG",
    "The f you say",
    "Toon 1",
    "Toon 2",
    "Toon 3",
    "Toon 4",
    "Toon 5",
    "TP Physique",
    "Trebble fart",
    "Tyler1",
    "V dorian",
    "V fromage",
    "Vampirisme",
    "Villager",
    "We got him",
    "We like Fortnite",
    "What it is",
    "What u on abt",
    "What",
    "windows",
    "WTC suicide",
    "xue",
    "Y u ge",
    "Y u run",
    "yamete",
    "Yaourt",
    "Yayeet",
    "Yeet",
]