//All mp3 filenames

const audioNames = [
    "A society",
    "Aaah",
    "Aah noo",
    "Ali-A",
    "Amaverjin",
    "AVC",
    "Ayeet",
    "Balls",
    "Bandicoot",
    "Baptiste",
    "Beep sheep",
    "Bing chilling",
    "Boswer",
    "Brain damage",
    "Brefs délais",
    "Chicks",
    "Choke",
    "Chomage",
    "Chug jug",
    "Cocaina",
    "Cyberchaj asmr",
    "Damage",
    "Despacito 2",
    "Despacito",
    "Diabeetus",
    "Disappointment",
    "Disperse fart",
    "DK rap",
    "Don't do it",
    "Drip",
    "Emergency",
    "Ennui",
    "Epee",
    "Ey wha",
    "Fart sound effect",
    "Fortnite default",
    "Funeste chorale",
    "Ga-non",
    "Geinoz-Cide",
    "Giraffe",
    "Grave fart",
    "Grill",
    "Gucci",
    "Hahuh",
    "Hanji",
    "Heebitch",
    "Help",
    "Humid fart",
    "It's Mario",
    "Jeff",
    "Juice",
    "K compote",
    "K feu",
    "K gra",
    "K pafo",
    "K poulette",
    "K pute",
    "K scorpion",
    "K sporadick",
    "K stache",
    "K Wales",
    "Lazy town",
    "Long fart",
    "Long name",
    "Loon fart",
    "Loudest orgasm",
    "Luke",
    "Mario fall",
    "Mario jump",
    "Mickey fart",
    "Mission failed",
    "Moan",
    "Moist",
    "Music",
    "Mwahaha",
    "Nani",
    "Negus",
    "New dog",
    "No sound",
    "Non",
    "Nuage",
    "Ogpt 2",
    "Ogpt 3",
    "Ogpt",
    "Pain",
    "Picnic",
    "Poop fart",
    "Projet",
    "Pufferfish",
    "Putin",
    "Question fart",
    "Quick fart",
    "Rasengan",
    "Real man",
    "Reverb fart",
    "Richelieu",
    "Samsung",
    "Sans feu",
    "Shart",
    "Short fart",
    "Shut up when I'm talking",
    "Sike",
    "Skrrra",
    "Snore",
    "Spaghet",
    "Spaghetti",
    "Speedrun",
    "Stegosaurus",
    "Stink fart",
    "Suck somebody",
    "Supercell",
    "Sus fart",
    "The f you say",
    "Toon 1",
    "Toon 2",
    "Toon 3",
    "Toon 4",
    "Toon 5",
    "Trebble fart",
    "Tyler1",
    "V dorian",
    "V fromage",
    "We got him",
    "We like Fortnite",
    "What it is",
    "What u on abt",
    "What",
    "Windows",
    "Xue",
    "Y u ge",
    "Y u run",
    "Yamete",
    "Yayeet",
    "Yeet",
]