//All mp3, svg data storage
    
const audioNames = [
    "a-aahno-nooh",
    "aaah",
    "amaverjine",
    "beepsheep",
    "bingchilling",
    "boswer",
    "boswerhaha",
    "braindamgae",
    "choke",
    "cvedir",
    "davidG",
    "diabeetus",
    "dkrap",
    "enui",
    "epe",
    "Fart Meme Sound",
    "Fart sound effect",
    "ga-non",
    "gamme",
    "grilled",
    "hanji",
    "heput",
    "jépapété",
    "Le Monke's Fart",
    "lotadamej",
    "Loudest orgasm ever EARRAPE",
    "mario_fall",
    "mario_triplejump",
    "mickeyfart",
    "moan",
    "newdog",
    "nodontdoit",
    "nop",
    "Normal Fart",
    "nuaj",
    "ogpt",
    "ogpt2",
    "ogpt3",
    "pet1",
    "pet10",
    "pet2",
    "pet3",
    "pet4",
    "pet5",
    "pet6",
    "pet7",
    "pet8",
    "pet9",
    "photo",
    "picnic",
    "projet",
    "Quick Reverb Fart",
    "realman",
    "richelieu",
    "samsung",
    "sanfe",
    "sike",
    "snore",
    "spaghet",
    "stegosaurus",
    "supercell",
    "toon1",
    "toon2",
    "toon3",
    "toon4",
    "toon5",
    "toon6",
    "trompet",
    "windows",
    "xue",
    "yamete",
    "yapadson",
    "yeet",
    "yrug",
    "yrurunin",
]