//All mp3, svg data storage
function audioByID(id) {
    return (data.filter(obj => obj.name == id)[0])
}

const data = [
    {name: "a-aahno-nooh", inList: true},
    {name: "aaah", inList: true},
    {name: "amaverjine", inList: true},
    {name: "beepsheep", inList: false},
    {name: "bingchilling", inList: true},
    {name: "boswer", inList: true},
    {name: "boswerhaha", inList: true},
    {name: "braindamgae", inList: true},
    {name: "choke", inList: true},
    {name: "cvedir", inList: false},
    {name: "davidG", inList: true},
    {name: "diabeetus", inList: true},
    {name: "dkrap", inList: true},
    {name: "enui", inList: true},
    {name: "epe", inList: true},
    {name: "Fart Meme Sound", inList: true},
    {name: "Fart sound effect", inList: true},
    {name: "ga-non", inList: true},
    {name: "gamme", inList: false},
    {name: "grilled", inList: true},
    {name: "hanji", inList: true},
    {name: "heput", inList: true},
    {name: "jépapété", inList: false},
    {name: "Le Monke's Fart Sound Effect", inList: true},
    {name: "lotadamej", inList: true},
    {name: "mario_fall", inList: true},
    {name: "mario_triplejump", inList: true},
    {name: "mickeyfart", inList: true},
    {name: "moan", inList: true},
    {name: "newdog", inList: true},
    {name: "nodontdoit", inList: true},
    {name: "nop", inList: true},
    {name: "Normal Fart Sound Effect.", inList: true},
    {name: "nuaj", inList: true},
    {name: "ogpt", inList: true},
    {name: "ogpt2", inList: false},
    {name: "ogpt3", inList: false},
    {name: "pet1", inList: true},
    {name: "pet10", inList: true},
    {name: "pet2", inList: true},
    {name: "pet3", inList: true},
    {name: "pet4", inList: true},
    {name: "pet5", inList: true},
    {name: "pet6", inList: true},
    {name: "pet7", inList: true},
    {name: "pet8", inList: true},
    {name: "pet9", inList: true},
    {name: "photo", inList: false},
    {name: "picnic", inList: true},
    {name: "projet", inList: true},
    {name: "Quick Reverb Fart - Sound Effect (HD)", inList: true},
    {name: "realman", inList: false},
    {name: "richelieu", inList: true},
    {name: "samsung", inList: true},
    {name: "sanfe", inList: true},
    {name: "sike", inList: true},
    {name: "snore", inList: true},
    {name: "spaghet", inList: true},
    {name: "stegosaurus", inList: false},
    {name: "supercell", inList: true},
    {name: "toon1", inList: true},
    {name: "toon2", inList: true},
    {name: "toon3", inList: true},
    {name: "toon4", inList: true},
    {name: "toon5", inList: true},
    {name: "toon6", inList: true},
    {name: "trompet", inList: false},
    {name: "windows", inList: true},
    {name: "xue", inList: true},
    {name: "yamete", inList: true},
    {name: "yapadson", inList: true},
    {name: "yeet", inList: true},
    {name: "yrug", inList: true},
    {name: "yrurunin", inList: true},
    {name: "Loudest orgasm ever EARRAPE", inList: true},
]